# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2

jobs:
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - run: node lib/index.js

workflows:
  version: 2
  release:
    jobs:
      - release